import os
import re
import py3Dmol

# ==========================================
#        STYLE SETTINGS (Unified)
# ==========================================

def apply_custom_style(view):
    """
    Applies the lab's consistent styling to any py3Dmol view.
    Used for both static structures and dynamic trajectories.
    """

    # Base style for every atom. The generic sphere makes atoms visible even
    # when the element field is missing or not recognized by py3Dmol.
    view.setStyle({
        'stick': {'color': '#999999', 'radius': 0.15},
        'sphere': {'color': '#B0B0B0', 'scale': 0.20}
    })

    s_scale = 0.25

    # Standard organic elements
    view.addStyle({'elem': 'C'}, {'sphere': {'color': '#32CD32', 'scale': s_scale}})
    view.addStyle({'elem': 'H'}, {'sphere': {'color': 'white',   'scale': s_scale}})
    view.addStyle({'elem': 'O'}, {'sphere': {'color': 'red',     'scale': s_scale}})
    view.addStyle({'elem': 'N'}, {'sphere': {'color': 'blue',    'scale': s_scale}})
    view.addStyle({'elem': 'S'}, {'sphere': {'color': 'orange',  'scale': s_scale}})
    view.addStyle({'elem': 'P'}, {'sphere': {'color': 'orange',  'scale': s_scale}})

    # Halogens
    view.addStyle({'elem': 'F'},  {'sphere': {'color': 'yellow',  'scale': s_scale}})
    view.addStyle({'elem': 'Cl'}, {'sphere': {'color': '#00FF00', 'scale': s_scale}})
    view.addStyle({'elem': 'Br'}, {'sphere': {'color': 'brown',   'scale': s_scale}})
    view.addStyle({'elem': 'I'},  {'sphere': {'color': 'purple',  'scale': s_scale}})

    # Special/dummy atoms
    view.addStyle({'elem': 'X'}, {'sphere': {'color': 'pink', 'scale': 0.4}})
    view.addStyle({'elem': 'R'}, {'sphere': {'color': 'pink', 'scale': 0.4}})


# ==========================================
#        INTERNAL HELPERS
# ==========================================

def _guess_element(atom_name):
    """Guess a chemical element from a PDB/GRO atom name."""
    letters = re.sub(r"[^A-Za-z]", "", atom_name or "").upper()
    if not letters:
        return "C"

    if letters.startswith("CL"):
        return "Cl"
    if letters.startswith("BR"):
        return "Br"

    first = letters[0]
    if first in ["H", "C", "N", "O", "S", "P", "F", "I"]:
        return first

    return "C"


def _fix_pdb_elements(pdb_text):
    """
    Add missing element fields to PDB ATOM/HETATM lines.

    This keeps hydrogens and oxygens visible/colored when PDB files generated by
    RDKit/MDAnalysis/Gromacs do not contain a proper element column.
    """
    fixed = []

    for line in pdb_text.splitlines():
        if line.startswith(("ATOM", "HETATM")):
            atom_name = line[12:16].strip() if len(line) >= 16 else ""
            element = line[76:78].strip() if len(line) >= 78 else ""

            if not element:
                element = _guess_element(atom_name)
                line = line[:76].ljust(76) + f"{element:>2s}" + line[78:]

        fixed.append(line)

    return "\n".join(fixed)


def _read_gro(gro_file):
    """Read atoms and box lengths from a GRO file."""
    with open(gro_file, "r") as handle:
        lines = handle.read().splitlines()

    if len(lines) < 3:
        raise ValueError(f"{gro_file} does not look like a valid GRO file.")

    n_atoms = int(lines[1].strip())
    atom_lines = lines[2:2 + n_atoms]
    box_nm = [float(x) for x in lines[2 + n_atoms].split()[:3]]

    atoms = []
    for line in atom_lines:
        resnr = int(line[0:5])
        resname = line[5:10].strip() or "POL"
        atomname = line[10:15].strip() or "C"
        x_nm = float(line[20:28])
        y_nm = float(line[28:36])
        z_nm = float(line[36:44])
        atoms.append((resnr, resname, atomname, x_nm, y_nm, z_nm))

    return atoms, box_nm


def _gro_to_pdb_block(gro_file):
    """Convert a GRO structure to a minimal PDB block for py3Dmol."""
    atoms, box_nm = _read_gro(gro_file)
    lx, ly, lz = [v * 10.0 for v in box_nm]  # nm -> Angstrom

    pdb_lines = [
        f"CRYST1{lx:9.3f}{ly:9.3f}{lz:9.3f}"
        f"{90.00:7.2f}{90.00:7.2f}{90.00:7.2f} P 1           1"
    ]

    for serial, (resnr, resname, atomname, x_nm, y_nm, z_nm) in enumerate(atoms, start=1):
        element = _guess_element(atomname)
        x, y, z = x_nm * 10.0, y_nm * 10.0, z_nm * 10.0

        pdb_lines.append(
            f"ATOM  {serial:5d} {atomname[:4]:>4s} {resname[:3]:>3s} A{resnr % 10000:4d}    "
            f"{x:8.3f}{y:8.3f}{z:8.3f}{1.00:6.2f}{0.00:6.2f}          {element:>2s}"
        )

    pdb_lines.append("END")
    return "\n".join(pdb_lines), box_nm


def _add_periodic_box_edges(view, box_nm):
    """Draw the edges of an orthorhombic periodic box."""
    if not box_nm:
        return

    lx, ly, lz = [float(v) * 10.0 for v in box_nm]  # nm -> Angstrom

    corners = [
        (0, 0, 0), (lx, 0, 0), (0, ly, 0), (0, 0, lz),
        (lx, ly, 0), (lx, 0, lz), (0, ly, lz), (lx, ly, lz),
    ]

    edges = [
        (0, 1), (0, 2), (0, 3),
        (1, 4), (1, 5),
        (2, 4), (2, 6),
        (3, 5), (3, 6),
        (4, 7), (5, 7), (6, 7),
    ]

    for i, j in edges:
        view.addLine({
            'start': {'x': corners[i][0], 'y': corners[i][1], 'z': corners[i][2]},
            'end':   {'x': corners[j][0], 'y': corners[j][1], 'z': corners[j][2]},
            'color': 'black',
            'linewidth': 2,
        })


# ==========================================
#        VISUALIZATION FUNCTIONS
# ==========================================

def show_structure(file_path_or_string, width=800, height=400, show_box="auto"):
    """
    Visualize a static MOL, PDB, or GRO structure with one consistent style.

    Examples
    --------
    view = show_structure("monomer.mol")
    view = show_structure("polymer.pdb")
    view = show_structure("bulk.gro", show_box=True)
    view.show()
    """
    view = py3Dmol.view(width=width, height=height)

    ext = "pdb"
    box_nm = None

    if os.path.exists(file_path_or_string):
        ext = file_path_or_string.split(".")[-1].lower()

        if ext == "gro":
            data, box_nm = _gro_to_pdb_block(file_path_or_string)
            fmt = "pdb"

        else:
            with open(file_path_or_string, "r") as handle:
                data = handle.read()

            if ext == "mol":
                fmt = "mol"
            else:
                data = _fix_pdb_elements(data)
                fmt = "pdb"

    else:
        # Assume raw molecular text.
        data = file_path_or_string
        fmt = "mol" if data.lstrip().startswith("@<TRIPOS>") else "pdb"
        if fmt == "pdb":
            data = _fix_pdb_elements(data)

    view.addModel(data, fmt)
    apply_custom_style(view)

    if show_box is True or (show_box == "auto" and ext == "gro"):
        _add_periodic_box_edges(view, box_nm)

    view.zoomTo()
    return view


def show_trajectory(pdb_content, width=800, height=400):
    """
    Visualize an animated PDB trajectory.
    This remains separate because trajectories use addModelsAsFrames().
    """
    view = py3Dmol.view(width=width, height=height)

    view.addModelsAsFrames(_fix_pdb_elements(pdb_content), 'pdb')
    apply_custom_style(view)

    view.animate({'loop': 'forward', 'reps': 50, 'step': 1, 'interval': 60})
    view.zoomTo()

    return view
