import os
import re
import py3Dmol


# ==========================================
#        STYLE SETTINGS (Unified)
# ==========================================

def apply_custom_style(view):
    """
    Applies the lab's consistent styling to any py3Dmol view.
    Used for both static structures and dynamic trajectories.
    """

    # Base style: gray sticks for all bonds
    view.setStyle({'stick': {'color': '#999999', 'radius': 0.15}})

    # Atom spheres
    s_scale = 0.25

    # Standard organic elements
    view.addStyle({'elem': 'C'},  {'sphere': {'color': '#32CD32', 'scale': s_scale}})
    view.addStyle({'elem': 'H'},  {'sphere': {'color': 'white',   'scale': s_scale}})
    view.addStyle({'elem': 'O'},  {'sphere': {'color': 'red',     'scale': s_scale}})
    view.addStyle({'elem': 'N'},  {'sphere': {'color': 'blue',    'scale': s_scale}})
    view.addStyle({'elem': 'S'},  {'sphere': {'color': 'orange',  'scale': s_scale}})
    view.addStyle({'elem': 'P'},  {'sphere': {'color': 'orange',  'scale': s_scale}})

    # Halogens
    view.addStyle({'elem': 'F'},  {'sphere': {'color': 'yellow',  'scale': s_scale}})
    view.addStyle({'elem': 'Cl'}, {'sphere': {'color': '#00FF00', 'scale': s_scale}})
    view.addStyle({'elem': 'Br'}, {'sphere': {'color': 'brown',   'scale': s_scale}})
    view.addStyle({'elem': 'I'},  {'sphere': {'color': 'purple',  'scale': s_scale}})

    # Dummy/linker atoms if present
    view.addStyle({'elem': 'X'}, {'sphere': {'color': 'pink', 'scale': 0.4}})
    view.addStyle({'elem': 'R'}, {'sphere': {'color': 'pink', 'scale': 0.4}})


# ==========================================
#        INTERNAL HELPERS
# ==========================================

def _guess_element(atom_name):
    """
    Guess a chemical element from an atom name.

    This is needed because PDB/GRO files generated by modelling tools can have
    missing or inconsistent element columns. We keep the logic simple and robust
    for organic/polymer systems.
    """
    name = (atom_name or "").strip()

    if not name:
        return "C"

    # Remove spaces and digits, keep letters only
    letters = re.sub(r"[^A-Za-z]", "", name)

    if not letters:
        return "C"

    upper = letters.upper()

    # Two-letter elements first
    if upper.startswith("CL"):
        return "Cl"
    if upper.startswith("BR"):
        return "Br"

    # Common organic/polymer elements
    first = upper[0]
    if first in ["H", "C", "N", "O", "S", "P", "F", "I"]:
        return first

    # Safe fallback for generic organic structures
    return "C"


def _normalize_pdb_block(pdb_text):
    """
    Rewrite ATOM/HETATM lines so that the element field is always populated.

    py3Dmol relies on the element field to apply element-specific styles.
    If the element column is missing or wrong, hydrogens and oxygens may not
    be visualized consistently.
    """
    out_lines = []

    for line in pdb_text.splitlines():
        if line.startswith(("ATOM", "HETATM")):
            atom_name = line[12:16].strip()
            element = _guess_element(atom_name)

            # Pad line to at least 78 chars, then overwrite element column.
            padded = line.ljust(78)
            fixed = padded[:76] + f"{element:>2s}" + padded[78:]
            out_lines.append(fixed)
        else:
            out_lines.append(line)

    return "\n".join(out_lines)


def _read_gro_file(gro_file):
    """
    Read a GRO file and return atom records plus box lengths.

    Coordinates in GRO are in nm.
    """
    with open(gro_file, "r") as handle:
        lines = handle.read().splitlines()

    if len(lines) < 3:
        raise ValueError(f"{gro_file} does not look like a valid GRO file.")

    try:
        n_atoms = int(lines[1].strip())
    except Exception as exc:
        raise ValueError(f"Could not read number of atoms from {gro_file}.") from exc

    atom_lines = lines[2:2 + n_atoms]

    if len(atom_lines) != n_atoms:
        raise ValueError(f"{gro_file} ended before all atoms were read.")

    box_line_index = 2 + n_atoms
    if box_line_index >= len(lines):
        raise ValueError(f"{gro_file} does not contain a box line.")

    box_parts = lines[box_line_index].split()
    if len(box_parts) < 3:
        raise ValueError(f"{gro_file} box line must contain at least 3 values.")

    box_nm = [float(x) for x in box_parts[:3]]

    atoms = []
    for line in atom_lines:
        # Standard GRO fixed-width columns
        resnr = int(line[0:5])
        resname = line[5:10].strip() or "POL"
        atomname = line[10:15].strip() or "C"
        atomnr = int(line[15:20])
        x_nm = float(line[20:28])
        y_nm = float(line[28:36])
        z_nm = float(line[36:44])

        atoms.append({
            "resnr": resnr,
            "resname": resname,
            "atomname": atomname,
            "atomnr": atomnr,
            "x_nm": x_nm,
            "y_nm": y_nm,
            "z_nm": z_nm,
        })

    return atoms, box_nm


def _gro_to_pdb_block(gro_file):
    """
    Convert GRO to a minimal PDB block for py3Dmol.

    GRO coordinates are in nm.
    PDB coordinates are in Angstrom.
    """
    atoms, box_nm = _read_gro_file(gro_file)

    lx, ly, lz = [v * 10.0 for v in box_nm]

    pdb_lines = [
        f"CRYST1{lx:9.3f}{ly:9.3f}{lz:9.3f}"
        f"{90.00:7.2f}{90.00:7.2f}{90.00:7.2f} P 1           1"
    ]

    for serial, atom in enumerate(atoms, start=1):
        atomname = atom["atomname"]
        resname = atom["resname"]
        resnr = atom["resnr"]
        x = atom["x_nm"] * 10.0
        y = atom["y_nm"] * 10.0
        z = atom["z_nm"] * 10.0
        element = _guess_element(atomname)

        pdb_lines.append(
            f"ATOM  {serial:5d} {atomname[:4]:>4s} {resname[:3]:>3s} A{resnr % 10000:4d}    "
            f"{x:8.3f}{y:8.3f}{z:8.3f}"
            f"{1.00:6.2f}{0.00:6.2f}          {element:>2s}"
        )

    pdb_lines.append("END")

    return "\n".join(pdb_lines), box_nm


def _add_periodic_box_edges(view, box_nm, color="black"):
    """
    Draw the edges of an orthorhombic periodic box in py3Dmol.

    box_nm is expected in nm.
    """
    if box_nm is None:
        return

    lx, ly, lz = [float(v) * 10.0 for v in box_nm]  # nm -> Angstrom

    corners = [
        (0.0, 0.0, 0.0),
        (lx, 0.0, 0.0),
        (0.0, ly, 0.0),
        (0.0, 0.0, lz),
        (lx, ly, 0.0),
        (lx, 0.0, lz),
        (0.0, ly, lz),
        (lx, ly, lz),
    ]

    edges = [
        (0, 1), (0, 2), (0, 3),
        (1, 4), (1, 5),
        (2, 4), (2, 6),
        (3, 5), (3, 6),
        (4, 7), (5, 7), (6, 7),
    ]

    for i, j in edges:
        x1, y1, z1 = corners[i]
        x2, y2, z2 = corners[j]

        view.addLine({
            "start": {"x": x1, "y": y1, "z": z1},
            "end": {"x": x2, "y": y2, "z": z2},
            "color": color,
            "linewidth": 2,
        })


# ==========================================
#        VISUALIZATION FUNCTIONS
# ==========================================

def show_structure(file_path_or_string, width=800, height=400, show_box="auto"):
    """
    Visualize a static molecular structure using one unified style.

    Supports:
    - MOL files
    - PDB files
    - GRO files
    - raw PDB/MOL strings

    Parameters
    ----------
    file_path_or_string : str
        Path to a .mol, .pdb or .gro file, or raw molecular text.
    width, height : int
        Viewer dimensions.
    show_box : bool or "auto"
        If True, draw the periodic box when available.
        If False, never draw it.
        If "auto", draw it automatically for GRO files.

    Returns
    -------
    py3Dmol.view
    """
    view = py3Dmol.view(width=width, height=height)

    box_nm = None
    ext = "pdb"

    if os.path.exists(file_path_or_string):
        ext = os.path.splitext(file_path_or_string)[1].lower().replace(".", "")

        if ext == "gro":
            data, box_nm = _gro_to_pdb_block(file_path_or_string)
            fmt = "pdb"

        elif ext == "mol":
            with open(file_path_or_string, "r") as handle:
                data = handle.read()
            fmt = "mol"

        else:
            with open(file_path_or_string, "r") as handle:
                data = handle.read()
            data = _normalize_pdb_block(data)
            fmt = "pdb"

    else:
        # Raw molecular string. Treat as PDB by default.
        data = _normalize_pdb_block(file_path_or_string)
        fmt = "pdb"

    view.addModel(data, fmt)
    apply_custom_style(view)

    if show_box is True or (show_box == "auto" and ext == "gro"):
        _add_periodic_box_edges(view, box_nm)

    view.zoomTo()
    return view


def show_trajectory(pdb_content, width=800, height=400):
    """
    Visualize an animated trajectory from a multi-frame PDB string.

    Parameters
    ----------
    pdb_content : str
        Multi-frame PDB content.
    width, height : int
        Viewer dimensions.

    Returns
    -------
    py3Dmol.view
    """
    view = py3Dmol.view(width=width, height=height)

    pdb_content = _normalize_pdb_block(pdb_content)

    view.addModelsAsFrames(pdb_content, "pdb")
    apply_custom_style(view)

    view.animate({
        "loop": "forward",
        "reps": 50,
        "step": 1,
        "interval": 60,
    })

    view.zoomTo()
    return view
